version: "3.8"

services:
  dcs-postgres:
    image: postgres:15.3-alpine
    container_name: dcs-postgres
    environment:
      POSTGRES_PASSWORD: Postgres2024!
      POSTGRES_USER: postgres
    ports:
      - 5433:5432
    volumes:
      - ./script/create-transational_db.sql:/docker-entrypoint-initdb.d/create-transational_db.sql
      - ./script/create-analytics_db.sql:/docker-entrypoint-initdb.d/create-analytics_db.sql